// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/billing/internal/adapters/driven/db/ent/generate/invoice"
	"go-link/billing/internal/adapters/driven/db/ent/generate/subscription"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvoiceCreate is the builder for creating a Invoice entity.
type InvoiceCreate struct {
	config
	mutation *InvoiceMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *InvoiceCreate) SetCreatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableCreatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InvoiceCreate) SetUpdatedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableUpdatedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *InvoiceCreate) SetDeletedAt(v time.Time) *InvoiceCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableDeletedAt(v *time.Time) *InvoiceCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *InvoiceCreate) SetDeletedBy(v int) *InvoiceCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableDeletedBy(v *int) *InvoiceCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetSubscriptionID sets the "subscription_id" field.
func (_c *InvoiceCreate) SetSubscriptionID(v int) *InvoiceCreate {
	_c.mutation.SetSubscriptionID(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *InvoiceCreate) SetTenantID(v int) *InvoiceCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetAmount sets the "amount" field.
func (_c *InvoiceCreate) SetAmount(v float64) *InvoiceCreate {
	_c.mutation.SetAmount(v)
	return _c
}

// SetCurrency sets the "currency" field.
func (_c *InvoiceCreate) SetCurrency(v string) *InvoiceCreate {
	_c.mutation.SetCurrency(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *InvoiceCreate) SetStatus(v invoice.Status) *InvoiceCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillableStatus(v *invoice.Status) *InvoiceCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPaymentID sets the "payment_id" field.
func (_c *InvoiceCreate) SetPaymentID(v string) *InvoiceCreate {
	_c.mutation.SetPaymentID(v)
	return _c
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_c *InvoiceCreate) SetNillablePaymentID(v *string) *InvoiceCreate {
	if v != nil {
		_c.SetPaymentID(*v)
	}
	return _c
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_c *InvoiceCreate) SetSubscription(v *Subscription) *InvoiceCreate {
	return _c.SetSubscriptionID(v.ID)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_c *InvoiceCreate) Mutation() *InvoiceMutation {
	return _c.mutation
}

// Save creates the Invoice in the database.
func (_c *InvoiceCreate) Save(ctx context.Context) (*Invoice, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InvoiceCreate) SaveX(ctx context.Context) *Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InvoiceCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if invoice.DefaultCreatedAt == nil {
			return fmt.Errorf("generate: uninitialized invoice.DefaultCreatedAt (forgotten import generate/runtime?)")
		}
		v := invoice.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if invoice.DefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized invoice.DefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := invoice.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := invoice.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *InvoiceCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "Invoice.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "Invoice.updated_at"`)}
	}
	if _, ok := _c.mutation.SubscriptionID(); !ok {
		return &ValidationError{Name: "subscription_id", err: errors.New(`generate: missing required field "Invoice.subscription_id"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`generate: missing required field "Invoice.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := invoice.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`generate: validator failed for field "Invoice.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`generate: missing required field "Invoice.amount"`)}
	}
	if _, ok := _c.mutation.Currency(); !ok {
		return &ValidationError{Name: "currency", err: errors.New(`generate: missing required field "Invoice.currency"`)}
	}
	if v, ok := _c.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`generate: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`generate: missing required field "Invoice.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`generate: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if len(_c.mutation.SubscriptionIDs()) == 0 {
		return &ValidationError{Name: "subscription", err: errors.New(`generate: missing required edge "Invoice.subscription"`)}
	}
	return nil
}

func (_c *InvoiceCreate) sqlSave(ctx context.Context) (*Invoice, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InvoiceCreate) createSpec() (*Invoice, *sqlgraph.CreateSpec) {
	var (
		_node = &Invoice{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(invoice.Table, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(invoice.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(invoice.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(invoice.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(invoice.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
		_node.Amount = value
	}
	if value, ok := _c.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
		_node.Currency = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.PaymentID(); ok {
		_spec.SetField(invoice.FieldPaymentID, field.TypeString, value)
		_node.PaymentID = value
	}
	if nodes := _c.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.SubscriptionTable,
			Columns: []string{invoice.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SubscriptionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertOne {
	_c.conflict = opts
	return &InvoiceUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreate) OnConflictColumns(columns ...string) *InvoiceUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertOne{
		create: _c,
	}
}

type (
	// InvoiceUpsertOne is the builder for "upsert"-ing
	//  one Invoice node.
	InvoiceUpsertOne struct {
		create *InvoiceCreate
	}

	// InvoiceUpsert is the "OnConflict" setter.
	InvoiceUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsert) SetUpdatedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateUpdatedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvoiceUpsert) SetDeletedAt(v time.Time) *InvoiceUpsert {
	u.Set(invoice.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateDeletedAt() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *InvoiceUpsert) ClearDeletedAt() *InvoiceUpsert {
	u.SetNull(invoice.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *InvoiceUpsert) SetDeletedBy(v int) *InvoiceUpsert {
	u.Set(invoice.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateDeletedBy() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *InvoiceUpsert) AddDeletedBy(v int) *InvoiceUpsert {
	u.Add(invoice.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *InvoiceUpsert) ClearDeletedBy() *InvoiceUpsert {
	u.SetNull(invoice.FieldDeletedBy)
	return u
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *InvoiceUpsert) SetSubscriptionID(v int) *InvoiceUpsert {
	u.Set(invoice.FieldSubscriptionID, v)
	return u
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateSubscriptionID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldSubscriptionID)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsert) SetTenantID(v int) *InvoiceUpsert {
	u.Set(invoice.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateTenantID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *InvoiceUpsert) AddTenantID(v int) *InvoiceUpsert {
	u.Add(invoice.FieldTenantID, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsert) SetAmount(v float64) *InvoiceUpsert {
	u.Set(invoice.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateAmount() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsert) AddAmount(v float64) *InvoiceUpsert {
	u.Add(invoice.FieldAmount, v)
	return u
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsert) SetCurrency(v string) *InvoiceUpsert {
	u.Set(invoice.FieldCurrency, v)
	return u
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateCurrency() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldCurrency)
	return u
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsert) SetStatus(v invoice.Status) *InvoiceUpsert {
	u.Set(invoice.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdateStatus() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldStatus)
	return u
}

// SetPaymentID sets the "payment_id" field.
func (u *InvoiceUpsert) SetPaymentID(v string) *InvoiceUpsert {
	u.Set(invoice.FieldPaymentID, v)
	return u
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *InvoiceUpsert) UpdatePaymentID() *InvoiceUpsert {
	u.SetExcluded(invoice.FieldPaymentID)
	return u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *InvoiceUpsert) ClearPaymentID() *InvoiceUpsert {
	u.SetNull(invoice.FieldPaymentID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertOne) UpdateNewValues() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(invoice.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InvoiceUpsertOne) Ignore() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertOne) DoNothing() *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreate.OnConflict
// documentation for more info.
func (u *InvoiceUpsertOne) Update(set func(*InvoiceUpsert)) *InvoiceUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertOne) SetUpdatedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateUpdatedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvoiceUpsertOne) SetDeletedAt(v time.Time) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateDeletedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *InvoiceUpsertOne) ClearDeletedAt() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *InvoiceUpsertOne) SetDeletedBy(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *InvoiceUpsertOne) AddDeletedBy(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateDeletedBy() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *InvoiceUpsertOne) ClearDeletedBy() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *InvoiceUpsertOne) SetSubscriptionID(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateSubscriptionID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsertOne) SetTenantID(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *InvoiceUpsertOne) AddTenantID(v int) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateTenantID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTenantID()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsertOne) SetAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsertOne) AddAmount(v float64) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateAmount() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertOne) SetCurrency(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateCurrency() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertOne) SetStatus(v invoice.Status) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdateStatus() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *InvoiceUpsertOne) SetPaymentID(v string) *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *InvoiceUpsertOne) UpdatePaymentID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *InvoiceUpsertOne) ClearPaymentID() *InvoiceUpsertOne {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearPaymentID()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for InvoiceCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InvoiceUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InvoiceUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *InvoiceCreate) SetID(id int) *InvoiceCreate {
	c.mutation.id = &id
	return c
}

// InvoiceCreateBulk is the builder for creating many Invoice entities in bulk.
type InvoiceCreateBulk struct {
	config
	err      error
	builders []*InvoiceCreate
	conflict []sql.ConflictOption
}

// Save creates the Invoice entities in the database.
func (_c *InvoiceCreateBulk) Save(ctx context.Context) ([]*Invoice, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Invoice, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InvoiceMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InvoiceCreateBulk) SaveX(ctx context.Context) []*Invoice {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InvoiceCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InvoiceCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Invoice.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InvoiceUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflict(opts ...sql.ConflictOption) *InvoiceUpsertBulk {
	_c.conflict = opts
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InvoiceCreateBulk) OnConflictColumns(columns ...string) *InvoiceUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InvoiceUpsertBulk{
		create: _c,
	}
}

// InvoiceUpsertBulk is the builder for "upsert"-ing
// a bulk of Invoice nodes.
type InvoiceUpsertBulk struct {
	create *InvoiceCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) UpdateNewValues() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(invoice.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Invoice.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InvoiceUpsertBulk) Ignore() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InvoiceUpsertBulk) DoNothing() *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InvoiceCreateBulk.OnConflict
// documentation for more info.
func (u *InvoiceUpsertBulk) Update(set func(*InvoiceUpsert)) *InvoiceUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InvoiceUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *InvoiceUpsertBulk) SetUpdatedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateUpdatedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *InvoiceUpsertBulk) SetDeletedAt(v time.Time) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateDeletedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *InvoiceUpsertBulk) ClearDeletedAt() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *InvoiceUpsertBulk) SetDeletedBy(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *InvoiceUpsertBulk) AddDeletedBy(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateDeletedBy() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *InvoiceUpsertBulk) ClearDeletedBy() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearDeletedBy()
	})
}

// SetSubscriptionID sets the "subscription_id" field.
func (u *InvoiceUpsertBulk) SetSubscriptionID(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetSubscriptionID(v)
	})
}

// UpdateSubscriptionID sets the "subscription_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateSubscriptionID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateSubscriptionID()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *InvoiceUpsertBulk) SetTenantID(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *InvoiceUpsertBulk) AddTenantID(v int) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateTenantID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateTenantID()
	})
}

// SetAmount sets the "amount" field.
func (u *InvoiceUpsertBulk) SetAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *InvoiceUpsertBulk) AddAmount(v float64) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateAmount() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateAmount()
	})
}

// SetCurrency sets the "currency" field.
func (u *InvoiceUpsertBulk) SetCurrency(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetCurrency(v)
	})
}

// UpdateCurrency sets the "currency" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateCurrency() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateCurrency()
	})
}

// SetStatus sets the "status" field.
func (u *InvoiceUpsertBulk) SetStatus(v invoice.Status) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdateStatus() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdateStatus()
	})
}

// SetPaymentID sets the "payment_id" field.
func (u *InvoiceUpsertBulk) SetPaymentID(v string) *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.SetPaymentID(v)
	})
}

// UpdatePaymentID sets the "payment_id" field to the value that was provided on create.
func (u *InvoiceUpsertBulk) UpdatePaymentID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.UpdatePaymentID()
	})
}

// ClearPaymentID clears the value of the "payment_id" field.
func (u *InvoiceUpsertBulk) ClearPaymentID() *InvoiceUpsertBulk {
	return u.Update(func(s *InvoiceUpsert) {
		s.ClearPaymentID()
	})
}

// Exec executes the query.
func (u *InvoiceUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the InvoiceCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for InvoiceCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InvoiceUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
