// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/billing/internal/adapters/driven/db/ent/generate/invoice"
	"go-link/billing/internal/adapters/driven/db/ent/generate/predicate"
	"go-link/billing/internal/adapters/driven/db/ent/generate/subscription"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// InvoiceUpdate is the builder for updating Invoice entities.
type InvoiceUpdate struct {
	config
	hooks     []Hook
	mutation  *InvoiceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdate) Where(ps ...predicate.Invoice) *InvoiceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdate) SetUpdatedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvoiceUpdate) SetDeletedAt(v time.Time) *InvoiceUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableDeletedAt(v *time.Time) *InvoiceUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InvoiceUpdate) ClearDeletedAt() *InvoiceUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *InvoiceUpdate) SetDeletedBy(v int) *InvoiceUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableDeletedBy(v *int) *InvoiceUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *InvoiceUpdate) AddDeletedBy(v int) *InvoiceUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *InvoiceUpdate) ClearDeletedBy() *InvoiceUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *InvoiceUpdate) SetSubscriptionID(v int) *InvoiceUpdate {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableSubscriptionID(v *int) *InvoiceUpdate {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InvoiceUpdate) SetTenantID(v int) *InvoiceUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableTenantID(v *int) *InvoiceUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *InvoiceUpdate) AddTenantID(v int) *InvoiceUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdate) SetAmount(v float64) *InvoiceUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableAmount(v *float64) *InvoiceUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdate) AddAmount(v float64) *InvoiceUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceUpdate) SetCurrency(v string) *InvoiceUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableCurrency(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdate) SetStatus(v invoice.Status) *InvoiceUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillableStatus(v *invoice.Status) *InvoiceUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *InvoiceUpdate) SetPaymentID(v string) *InvoiceUpdate {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *InvoiceUpdate) SetNillablePaymentID(v *string) *InvoiceUpdate {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (_u *InvoiceUpdate) ClearPaymentID() *InvoiceUpdate {
	_u.mutation.ClearPaymentID()
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *InvoiceUpdate) SetSubscription(v *Subscription) *InvoiceUpdate {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdate) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *InvoiceUpdate) ClearSubscription() *InvoiceUpdate {
	_u.mutation.ClearSubscription()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InvoiceUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InvoiceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if invoice.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized invoice.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdate) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := invoice.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`generate: validator failed for field "Invoice.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`generate: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`generate: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "Invoice.subscription"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvoiceUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvoiceUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvoiceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invoice.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(invoice.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(invoice.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(invoice.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(invoice.FieldDeletedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(invoice.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(invoice.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(invoice.FieldPaymentID, field.TypeString, value)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(invoice.FieldPaymentID, field.TypeString)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.SubscriptionTable,
			Columns: []string{invoice.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.SubscriptionTable,
			Columns: []string{invoice.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InvoiceUpdateOne is the builder for updating a single Invoice entity.
type InvoiceUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *InvoiceMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *InvoiceUpdateOne) SetUpdatedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *InvoiceUpdateOne) SetDeletedAt(v time.Time) *InvoiceUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableDeletedAt(v *time.Time) *InvoiceUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *InvoiceUpdateOne) ClearDeletedAt() *InvoiceUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *InvoiceUpdateOne) SetDeletedBy(v int) *InvoiceUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableDeletedBy(v *int) *InvoiceUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *InvoiceUpdateOne) AddDeletedBy(v int) *InvoiceUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *InvoiceUpdateOne) ClearDeletedBy() *InvoiceUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetSubscriptionID sets the "subscription_id" field.
func (_u *InvoiceUpdateOne) SetSubscriptionID(v int) *InvoiceUpdateOne {
	_u.mutation.SetSubscriptionID(v)
	return _u
}

// SetNillableSubscriptionID sets the "subscription_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableSubscriptionID(v *int) *InvoiceUpdateOne {
	if v != nil {
		_u.SetSubscriptionID(*v)
	}
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InvoiceUpdateOne) SetTenantID(v int) *InvoiceUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableTenantID(v *int) *InvoiceUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *InvoiceUpdateOne) AddTenantID(v int) *InvoiceUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *InvoiceUpdateOne) SetAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableAmount(v *float64) *InvoiceUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *InvoiceUpdateOne) AddAmount(v float64) *InvoiceUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *InvoiceUpdateOne) SetCurrency(v string) *InvoiceUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableCurrency(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *InvoiceUpdateOne) SetStatus(v invoice.Status) *InvoiceUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillableStatus(v *invoice.Status) *InvoiceUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaymentID sets the "payment_id" field.
func (_u *InvoiceUpdateOne) SetPaymentID(v string) *InvoiceUpdateOne {
	_u.mutation.SetPaymentID(v)
	return _u
}

// SetNillablePaymentID sets the "payment_id" field if the given value is not nil.
func (_u *InvoiceUpdateOne) SetNillablePaymentID(v *string) *InvoiceUpdateOne {
	if v != nil {
		_u.SetPaymentID(*v)
	}
	return _u
}

// ClearPaymentID clears the value of the "payment_id" field.
func (_u *InvoiceUpdateOne) ClearPaymentID() *InvoiceUpdateOne {
	_u.mutation.ClearPaymentID()
	return _u
}

// SetSubscription sets the "subscription" edge to the Subscription entity.
func (_u *InvoiceUpdateOne) SetSubscription(v *Subscription) *InvoiceUpdateOne {
	return _u.SetSubscriptionID(v.ID)
}

// Mutation returns the InvoiceMutation object of the builder.
func (_u *InvoiceUpdateOne) Mutation() *InvoiceMutation {
	return _u.mutation
}

// ClearSubscription clears the "subscription" edge to the Subscription entity.
func (_u *InvoiceUpdateOne) ClearSubscription() *InvoiceUpdateOne {
	_u.mutation.ClearSubscription()
	return _u
}

// Where appends a list predicates to the InvoiceUpdate builder.
func (_u *InvoiceUpdateOne) Where(ps ...predicate.Invoice) *InvoiceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InvoiceUpdateOne) Select(field string, fields ...string) *InvoiceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Invoice entity.
func (_u *InvoiceUpdateOne) Save(ctx context.Context) (*Invoice, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InvoiceUpdateOne) SaveX(ctx context.Context) *Invoice {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InvoiceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InvoiceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *InvoiceUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if invoice.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized invoice.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := invoice.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *InvoiceUpdateOne) check() error {
	if v, ok := _u.mutation.TenantID(); ok {
		if err := invoice.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`generate: validator failed for field "Invoice.tenant_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Currency(); ok {
		if err := invoice.CurrencyValidator(v); err != nil {
			return &ValidationError{Name: "currency", err: fmt.Errorf(`generate: validator failed for field "Invoice.currency": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := invoice.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`generate: validator failed for field "Invoice.status": %w`, err)}
		}
	}
	if _u.mutation.SubscriptionCleared() && len(_u.mutation.SubscriptionIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "Invoice.subscription"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *InvoiceUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *InvoiceUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *InvoiceUpdateOne) sqlSave(ctx context.Context) (_node *Invoice, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(invoice.Table, invoice.Columns, sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "Invoice.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, invoice.FieldID)
		for _, f := range fields {
			if !invoice.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != invoice.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(invoice.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(invoice.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(invoice.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(invoice.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(invoice.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(invoice.FieldDeletedBy, field.TypeInt)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(invoice.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(invoice.FieldTenantID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(invoice.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(invoice.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(invoice.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentID(); ok {
		_spec.SetField(invoice.FieldPaymentID, field.TypeString, value)
	}
	if _u.mutation.PaymentIDCleared() {
		_spec.ClearField(invoice.FieldPaymentID, field.TypeString)
	}
	if _u.mutation.SubscriptionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.SubscriptionTable,
			Columns: []string{invoice.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   invoice.SubscriptionTable,
			Columns: []string{invoice.SubscriptionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Invoice{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{invoice.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
