// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/billing/internal/adapters/driven/db/ent/generate/invoice"
	"go-link/billing/internal/adapters/driven/db/ent/generate/plan"
	"go-link/billing/internal/adapters/driven/db/ent/generate/subscription"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscriptionCreate is the builder for creating a Subscription entity.
type SubscriptionCreate struct {
	config
	mutation *SubscriptionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *SubscriptionCreate) SetCreatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCreatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SubscriptionCreate) SetUpdatedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableUpdatedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SubscriptionCreate) SetDeletedAt(v time.Time) *SubscriptionCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableDeletedAt(v *time.Time) *SubscriptionCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *SubscriptionCreate) SetDeletedBy(v int) *SubscriptionCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableDeletedBy(v *int) *SubscriptionCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *SubscriptionCreate) SetTenantID(v int) *SubscriptionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *SubscriptionCreate) SetPlanID(v int) *SubscriptionCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *SubscriptionCreate) SetStatus(v subscription.Status) *SubscriptionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableStatus(v *subscription.Status) *SubscriptionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (_c *SubscriptionCreate) SetCurrentPeriodStart(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCurrentPeriodStart(v)
	return _c
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (_c *SubscriptionCreate) SetCurrentPeriodEnd(v time.Time) *SubscriptionCreate {
	_c.mutation.SetCurrentPeriodEnd(v)
	return _c
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (_c *SubscriptionCreate) SetCancelAtPeriodEnd(v bool) *SubscriptionCreate {
	_c.mutation.SetCancelAtPeriodEnd(v)
	return _c
}

// SetNillableCancelAtPeriodEnd sets the "cancel_at_period_end" field if the given value is not nil.
func (_c *SubscriptionCreate) SetNillableCancelAtPeriodEnd(v *bool) *SubscriptionCreate {
	if v != nil {
		_c.SetCancelAtPeriodEnd(*v)
	}
	return _c
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_c *SubscriptionCreate) SetPlan(v *Plan) *SubscriptionCreate {
	return _c.SetPlanID(v.ID)
}

// AddInvoiceIDs adds the "invoices" edge to the Invoice entity by IDs.
func (_c *SubscriptionCreate) AddInvoiceIDs(ids ...int) *SubscriptionCreate {
	_c.mutation.AddInvoiceIDs(ids...)
	return _c
}

// AddInvoices adds the "invoices" edges to the Invoice entity.
func (_c *SubscriptionCreate) AddInvoices(v ...*Invoice) *SubscriptionCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInvoiceIDs(ids...)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_c *SubscriptionCreate) Mutation() *SubscriptionMutation {
	return _c.mutation
}

// Save creates the Subscription in the database.
func (_c *SubscriptionCreate) Save(ctx context.Context) (*Subscription, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubscriptionCreate) SaveX(ctx context.Context) *Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubscriptionCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if subscription.DefaultCreatedAt == nil {
			return fmt.Errorf("generate: uninitialized subscription.DefaultCreatedAt (forgotten import generate/runtime?)")
		}
		v := subscription.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if subscription.DefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized subscription.DefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := subscription.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := subscription.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		v := subscription.DefaultCancelAtPeriodEnd
		_c.mutation.SetCancelAtPeriodEnd(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubscriptionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "Subscription.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "Subscription.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`generate: missing required field "Subscription.tenant_id"`)}
	}
	if v, ok := _c.mutation.TenantID(); ok {
		if err := subscription.TenantIDValidator(v); err != nil {
			return &ValidationError{Name: "tenant_id", err: fmt.Errorf(`generate: validator failed for field "Subscription.tenant_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`generate: missing required field "Subscription.plan_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`generate: missing required field "Subscription.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := subscription.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`generate: validator failed for field "Subscription.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentPeriodStart(); !ok {
		return &ValidationError{Name: "current_period_start", err: errors.New(`generate: missing required field "Subscription.current_period_start"`)}
	}
	if _, ok := _c.mutation.CurrentPeriodEnd(); !ok {
		return &ValidationError{Name: "current_period_end", err: errors.New(`generate: missing required field "Subscription.current_period_end"`)}
	}
	if _, ok := _c.mutation.CancelAtPeriodEnd(); !ok {
		return &ValidationError{Name: "cancel_at_period_end", err: errors.New(`generate: missing required field "Subscription.cancel_at_period_end"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`generate: missing required edge "Subscription.plan"`)}
	}
	return nil
}

func (_c *SubscriptionCreate) sqlSave(ctx context.Context) (*Subscription, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubscriptionCreate) createSpec() (*Subscription, *sqlgraph.CreateSpec) {
	var (
		_node = &Subscription{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(subscription.Table, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(subscription.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(subscription.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(subscription.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(subscription.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(subscription.FieldTenantID, field.TypeInt, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CurrentPeriodStart(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodStart, field.TypeTime, value)
		_node.CurrentPeriodStart = value
	}
	if value, ok := _c.mutation.CurrentPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCurrentPeriodEnd, field.TypeTime, value)
		_node.CurrentPeriodEnd = value
	}
	if value, ok := _c.mutation.CancelAtPeriodEnd(); ok {
		_spec.SetField(subscription.FieldCancelAtPeriodEnd, field.TypeBool, value)
		_node.CancelAtPeriodEnd = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InvoicesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subscription.InvoicesTable,
			Columns: []string{subscription.InvoicesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invoice.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subscription.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionCreate) OnConflict(opts ...sql.ConflictOption) *SubscriptionUpsertOne {
	_c.conflict = opts
	return &SubscriptionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionCreate) OnConflictColumns(columns ...string) *SubscriptionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionUpsertOne{
		create: _c,
	}
}

type (
	// SubscriptionUpsertOne is the builder for "upsert"-ing
	//  one Subscription node.
	SubscriptionUpsertOne struct {
		create *SubscriptionCreate
	}

	// SubscriptionUpsert is the "OnConflict" setter.
	SubscriptionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsert) SetUpdatedAt(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateUpdatedAt() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionUpsert) SetDeletedAt(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateDeletedAt() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionUpsert) ClearDeletedAt() *SubscriptionUpsert {
	u.SetNull(subscription.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SubscriptionUpsert) SetDeletedBy(v int) *SubscriptionUpsert {
	u.Set(subscription.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateDeletedBy() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *SubscriptionUpsert) AddDeletedBy(v int) *SubscriptionUpsert {
	u.Add(subscription.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SubscriptionUpsert) ClearDeletedBy() *SubscriptionUpsert {
	u.SetNull(subscription.FieldDeletedBy)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *SubscriptionUpsert) SetTenantID(v int) *SubscriptionUpsert {
	u.Set(subscription.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateTenantID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SubscriptionUpsert) AddTenantID(v int) *SubscriptionUpsert {
	u.Add(subscription.FieldTenantID, v)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionUpsert) SetPlanID(v int) *SubscriptionUpsert {
	u.Set(subscription.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdatePlanID() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldPlanID)
	return u
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsert) SetStatus(v subscription.Status) *SubscriptionUpsert {
	u.Set(subscription.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateStatus() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldStatus)
	return u
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *SubscriptionUpsert) SetCurrentPeriodStart(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldCurrentPeriodStart, v)
	return u
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateCurrentPeriodStart() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldCurrentPeriodStart)
	return u
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsert) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsert {
	u.Set(subscription.FieldCurrentPeriodEnd, v)
	return u
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateCurrentPeriodEnd() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldCurrentPeriodEnd)
	return u
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsert) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsert {
	u.Set(subscription.FieldCancelAtPeriodEnd, v)
	return u
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsert) UpdateCancelAtPeriodEnd() *SubscriptionUpsert {
	u.SetExcluded(subscription.FieldCancelAtPeriodEnd)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionUpsertOne) UpdateNewValues() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(subscription.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SubscriptionUpsertOne) Ignore() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionUpsertOne) DoNothing() *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionCreate.OnConflict
// documentation for more info.
func (u *SubscriptionUpsertOne) Update(set func(*SubscriptionUpsert)) *SubscriptionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsertOne) SetUpdatedAt(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateUpdatedAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionUpsertOne) SetDeletedAt(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateDeletedAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionUpsertOne) ClearDeletedAt() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SubscriptionUpsertOne) SetDeletedBy(v int) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *SubscriptionUpsertOne) AddDeletedBy(v int) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateDeletedBy() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SubscriptionUpsertOne) ClearDeletedBy() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *SubscriptionUpsertOne) SetTenantID(v int) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SubscriptionUpsertOne) AddTenantID(v int) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateTenantID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionUpsertOne) SetPlanID(v int) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdatePlanID() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsertOne) SetStatus(v subscription.Status) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateStatus() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *SubscriptionUpsertOne) SetCurrentPeriodStart(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateCurrentPeriodStart() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsertOne) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateCurrentPeriodEnd() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsertOne) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertOne) UpdateCancelAtPeriodEnd() *SubscriptionUpsertOne {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// Exec executes the query.
func (u *SubscriptionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for SubscriptionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SubscriptionUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SubscriptionUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *SubscriptionCreate) SetID(id int) *SubscriptionCreate {
	c.mutation.id = &id
	return c
}

// SubscriptionCreateBulk is the builder for creating many Subscription entities in bulk.
type SubscriptionCreateBulk struct {
	config
	err      error
	builders []*SubscriptionCreate
	conflict []sql.ConflictOption
}

// Save creates the Subscription entities in the database.
func (_c *SubscriptionCreateBulk) Save(ctx context.Context) ([]*Subscription, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Subscription, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubscriptionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) SaveX(ctx context.Context) []*Subscription {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubscriptionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubscriptionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Subscription.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SubscriptionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SubscriptionCreateBulk) OnConflict(opts ...sql.ConflictOption) *SubscriptionUpsertBulk {
	_c.conflict = opts
	return &SubscriptionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SubscriptionCreateBulk) OnConflictColumns(columns ...string) *SubscriptionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SubscriptionUpsertBulk{
		create: _c,
	}
}

// SubscriptionUpsertBulk is the builder for "upsert"-ing
// a bulk of Subscription nodes.
type SubscriptionUpsertBulk struct {
	create *SubscriptionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SubscriptionUpsertBulk) UpdateNewValues() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(subscription.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Subscription.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SubscriptionUpsertBulk) Ignore() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SubscriptionUpsertBulk) DoNothing() *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SubscriptionCreateBulk.OnConflict
// documentation for more info.
func (u *SubscriptionUpsertBulk) Update(set func(*SubscriptionUpsert)) *SubscriptionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SubscriptionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SubscriptionUpsertBulk) SetUpdatedAt(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateUpdatedAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SubscriptionUpsertBulk) SetDeletedAt(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateDeletedAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SubscriptionUpsertBulk) ClearDeletedAt() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *SubscriptionUpsertBulk) SetDeletedBy(v int) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *SubscriptionUpsertBulk) AddDeletedBy(v int) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateDeletedBy() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *SubscriptionUpsertBulk) ClearDeletedBy() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *SubscriptionUpsertBulk) SetTenantID(v int) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *SubscriptionUpsertBulk) AddTenantID(v int) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateTenantID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateTenantID()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *SubscriptionUpsertBulk) SetPlanID(v int) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdatePlanID() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdatePlanID()
	})
}

// SetStatus sets the "status" field.
func (u *SubscriptionUpsertBulk) SetStatus(v subscription.Status) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateStatus() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateStatus()
	})
}

// SetCurrentPeriodStart sets the "current_period_start" field.
func (u *SubscriptionUpsertBulk) SetCurrentPeriodStart(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodStart(v)
	})
}

// UpdateCurrentPeriodStart sets the "current_period_start" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateCurrentPeriodStart() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodStart()
	})
}

// SetCurrentPeriodEnd sets the "current_period_end" field.
func (u *SubscriptionUpsertBulk) SetCurrentPeriodEnd(v time.Time) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCurrentPeriodEnd(v)
	})
}

// UpdateCurrentPeriodEnd sets the "current_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateCurrentPeriodEnd() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCurrentPeriodEnd()
	})
}

// SetCancelAtPeriodEnd sets the "cancel_at_period_end" field.
func (u *SubscriptionUpsertBulk) SetCancelAtPeriodEnd(v bool) *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.SetCancelAtPeriodEnd(v)
	})
}

// UpdateCancelAtPeriodEnd sets the "cancel_at_period_end" field to the value that was provided on create.
func (u *SubscriptionUpsertBulk) UpdateCancelAtPeriodEnd() *SubscriptionUpsertBulk {
	return u.Update(func(s *SubscriptionUpsert) {
		s.UpdateCancelAtPeriodEnd()
	})
}

// Exec executes the query.
func (u *SubscriptionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the SubscriptionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for SubscriptionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SubscriptionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
