// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/identity/internal/adapters/driven/db/ent/generate/domain"
	"go-link/identity/internal/adapters/driven/db/ent/generate/tenant"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DomainCreate is the builder for creating a Domain entity.
type DomainCreate struct {
	config
	mutation *DomainMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DomainCreate) SetCreatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableCreatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DomainCreate) SetUpdatedAt(v time.Time) *DomainCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableUpdatedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *DomainCreate) SetDeletedAt(v time.Time) *DomainCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *DomainCreate) SetNillableDeletedAt(v *time.Time) *DomainCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *DomainCreate) SetDeletedBy(v int) *DomainCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *DomainCreate) SetNillableDeletedBy(v *int) *DomainCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetDomain sets the "domain" field.
func (_c *DomainCreate) SetDomain(v string) *DomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *DomainCreate) SetTenantID(v int) *DomainCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetIsVerified sets the "is_verified" field.
func (_c *DomainCreate) SetIsVerified(v bool) *DomainCreate {
	_c.mutation.SetIsVerified(v)
	return _c
}

// SetNillableIsVerified sets the "is_verified" field if the given value is not nil.
func (_c *DomainCreate) SetNillableIsVerified(v *bool) *DomainCreate {
	if v != nil {
		_c.SetIsVerified(*v)
	}
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *DomainCreate) SetTenant(v *Tenant) *DomainCreate {
	return _c.SetTenantID(v.ID)
}

// Mutation returns the DomainMutation object of the builder.
func (_c *DomainCreate) Mutation() *DomainMutation {
	return _c.mutation
}

// Save creates the Domain in the database.
func (_c *DomainCreate) Save(ctx context.Context) (*Domain, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DomainCreate) SaveX(ctx context.Context) *Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DomainCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if domain.DefaultCreatedAt == nil {
			return fmt.Errorf("generate: uninitialized domain.DefaultCreatedAt (forgotten import generate/runtime?)")
		}
		v := domain.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if domain.DefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized domain.DefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := domain.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		v := domain.DefaultIsVerified
		_c.mutation.SetIsVerified(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *DomainCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "Domain.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "Domain.updated_at"`)}
	}
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`generate: missing required field "Domain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := domain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`generate: validator failed for field "Domain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`generate: missing required field "Domain.tenant_id"`)}
	}
	if _, ok := _c.mutation.IsVerified(); !ok {
		return &ValidationError{Name: "is_verified", err: errors.New(`generate: missing required field "Domain.is_verified"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`generate: missing required edge "Domain.tenant"`)}
	}
	return nil
}

func (_c *DomainCreate) sqlSave(ctx context.Context) (*Domain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DomainCreate) createSpec() (*Domain, *sqlgraph.CreateSpec) {
	var (
		_node = &Domain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(domain.Table, sqlgraph.NewFieldSpec(domain.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(domain.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(domain.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(domain.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(domain.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(domain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := _c.mutation.IsVerified(); ok {
		_spec.SetField(domain.FieldIsVerified, field.TypeBool, value)
		_node.IsVerified = value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   domain.TenantTable,
			Columns: []string{domain.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Domain.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DomainCreate) OnConflict(opts ...sql.ConflictOption) *DomainUpsertOne {
	_c.conflict = opts
	return &DomainUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DomainCreate) OnConflictColumns(columns ...string) *DomainUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DomainUpsertOne{
		create: _c,
	}
}

type (
	// DomainUpsertOne is the builder for "upsert"-ing
	//  one Domain node.
	DomainUpsertOne struct {
		create *DomainCreate
	}

	// DomainUpsert is the "OnConflict" setter.
	DomainUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsert) SetUpdatedAt(v time.Time) *DomainUpsert {
	u.Set(domain.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsert) UpdateUpdatedAt() *DomainUpsert {
	u.SetExcluded(domain.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DomainUpsert) SetDeletedAt(v time.Time) *DomainUpsert {
	u.Set(domain.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DomainUpsert) UpdateDeletedAt() *DomainUpsert {
	u.SetExcluded(domain.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DomainUpsert) ClearDeletedAt() *DomainUpsert {
	u.SetNull(domain.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DomainUpsert) SetDeletedBy(v int) *DomainUpsert {
	u.Set(domain.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DomainUpsert) UpdateDeletedBy() *DomainUpsert {
	u.SetExcluded(domain.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DomainUpsert) AddDeletedBy(v int) *DomainUpsert {
	u.Add(domain.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DomainUpsert) ClearDeletedBy() *DomainUpsert {
	u.SetNull(domain.FieldDeletedBy)
	return u
}

// SetDomain sets the "domain" field.
func (u *DomainUpsert) SetDomain(v string) *DomainUpsert {
	u.Set(domain.FieldDomain, v)
	return u
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DomainUpsert) UpdateDomain() *DomainUpsert {
	u.SetExcluded(domain.FieldDomain)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsert) SetTenantID(v int) *DomainUpsert {
	u.Set(domain.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsert) UpdateTenantID() *DomainUpsert {
	u.SetExcluded(domain.FieldTenantID)
	return u
}

// SetIsVerified sets the "is_verified" field.
func (u *DomainUpsert) SetIsVerified(v bool) *DomainUpsert {
	u.Set(domain.FieldIsVerified, v)
	return u
}

// UpdateIsVerified sets the "is_verified" field to the value that was provided on create.
func (u *DomainUpsert) UpdateIsVerified() *DomainUpsert {
	u.SetExcluded(domain.FieldIsVerified)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DomainUpsertOne) UpdateNewValues() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(domain.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DomainUpsertOne) Ignore() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DomainUpsertOne) DoNothing() *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DomainCreate.OnConflict
// documentation for more info.
func (u *DomainUpsertOne) Update(set func(*DomainUpsert)) *DomainUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsertOne) SetUpdatedAt(v time.Time) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateUpdatedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DomainUpsertOne) SetDeletedAt(v time.Time) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateDeletedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DomainUpsertOne) ClearDeletedAt() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DomainUpsertOne) SetDeletedBy(v int) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DomainUpsertOne) AddDeletedBy(v int) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateDeletedBy() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DomainUpsertOne) ClearDeletedBy() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.ClearDeletedBy()
	})
}

// SetDomain sets the "domain" field.
func (u *DomainUpsertOne) SetDomain(v string) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateDomain() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDomain()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsertOne) SetTenantID(v int) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateTenantID() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateTenantID()
	})
}

// SetIsVerified sets the "is_verified" field.
func (u *DomainUpsertOne) SetIsVerified(v bool) *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.SetIsVerified(v)
	})
}

// UpdateIsVerified sets the "is_verified" field to the value that was provided on create.
func (u *DomainUpsertOne) UpdateIsVerified() *DomainUpsertOne {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateIsVerified()
	})
}

// Exec executes the query.
func (u *DomainUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for DomainCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DomainUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DomainUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DomainUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *DomainCreate) SetID(id int) *DomainCreate {
	c.mutation.id = &id
	return c
}

// DomainCreateBulk is the builder for creating many Domain entities in bulk.
type DomainCreateBulk struct {
	config
	err      error
	builders []*DomainCreate
	conflict []sql.ConflictOption
}

// Save creates the Domain entities in the database.
func (_c *DomainCreateBulk) Save(ctx context.Context) ([]*Domain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Domain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DomainCreateBulk) SaveX(ctx context.Context) []*Domain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Domain.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DomainUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DomainCreateBulk) OnConflict(opts ...sql.ConflictOption) *DomainUpsertBulk {
	_c.conflict = opts
	return &DomainUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DomainCreateBulk) OnConflictColumns(columns ...string) *DomainUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DomainUpsertBulk{
		create: _c,
	}
}

// DomainUpsertBulk is the builder for "upsert"-ing
// a bulk of Domain nodes.
type DomainUpsertBulk struct {
	create *DomainCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DomainUpsertBulk) UpdateNewValues() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(domain.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Domain.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DomainUpsertBulk) Ignore() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DomainUpsertBulk) DoNothing() *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DomainCreateBulk.OnConflict
// documentation for more info.
func (u *DomainUpsertBulk) Update(set func(*DomainUpsert)) *DomainUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DomainUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DomainUpsertBulk) SetUpdatedAt(v time.Time) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateUpdatedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *DomainUpsertBulk) SetDeletedAt(v time.Time) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateDeletedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *DomainUpsertBulk) ClearDeletedAt() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *DomainUpsertBulk) SetDeletedBy(v int) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *DomainUpsertBulk) AddDeletedBy(v int) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateDeletedBy() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *DomainUpsertBulk) ClearDeletedBy() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.ClearDeletedBy()
	})
}

// SetDomain sets the "domain" field.
func (u *DomainUpsertBulk) SetDomain(v string) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetDomain(v)
	})
}

// UpdateDomain sets the "domain" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateDomain() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateDomain()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *DomainUpsertBulk) SetTenantID(v int) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateTenantID() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateTenantID()
	})
}

// SetIsVerified sets the "is_verified" field.
func (u *DomainUpsertBulk) SetIsVerified(v bool) *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.SetIsVerified(v)
	})
}

// UpdateIsVerified sets the "is_verified" field to the value that was provided on create.
func (u *DomainUpsertBulk) UpdateIsVerified() *DomainUpsertBulk {
	return u.Update(func(s *DomainUpsert) {
		s.UpdateIsVerified()
	})
}

// Exec executes the query.
func (u *DomainUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the DomainCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for DomainCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DomainUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
