// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/identity/internal/adapters/driven/db/ent/generate/predicate"
	"go-link/identity/internal/adapters/driven/db/ent/generate/role"
	"go-link/identity/internal/adapters/driven/db/ent/generate/tenant"
	"go-link/identity/internal/adapters/driven/db/ent/generate/tenantmember"
	"go-link/identity/internal/adapters/driven/db/ent/generate/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantMemberUpdate is the builder for updating TenantMember entities.
type TenantMemberUpdate struct {
	config
	hooks     []Hook
	mutation  *TenantMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TenantMemberUpdate builder.
func (_u *TenantMemberUpdate) Where(ps ...predicate.TenantMember) *TenantMemberUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMemberUpdate) SetUpdatedAt(v time.Time) *TenantMemberUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantMemberUpdate) SetDeletedAt(v time.Time) *TenantMemberUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableDeletedAt(v *time.Time) *TenantMemberUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantMemberUpdate) ClearDeletedAt() *TenantMemberUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TenantMemberUpdate) SetDeletedBy(v int) *TenantMemberUpdate {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableDeletedBy(v *int) *TenantMemberUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TenantMemberUpdate) AddDeletedBy(v int) *TenantMemberUpdate {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TenantMemberUpdate) ClearDeletedBy() *TenantMemberUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMemberUpdate) SetTenantID(v int) *TenantMemberUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableTenantID(v *int) *TenantMemberUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantMemberUpdate) SetUserID(v int) *TenantMemberUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableUserID(v *int) *TenantMemberUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *TenantMemberUpdate) SetRoleID(v int) *TenantMemberUpdate {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *TenantMemberUpdate) SetNillableRoleID(v *int) *TenantMemberUpdate {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdate) SetTenant(v *Tenant) *TenantMemberUpdate {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMemberUpdate) SetUser(v *User) *TenantMemberUpdate {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *TenantMemberUpdate) SetRole(v *Role) *TenantMemberUpdate {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the TenantMemberMutation object of the builder.
func (_u *TenantMemberUpdate) Mutation() *TenantMemberMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdate) ClearTenant() *TenantMemberUpdate {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMemberUpdate) ClearUser() *TenantMemberUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *TenantMemberUpdate) ClearRole() *TenantMemberUpdate {
	_u.mutation.ClearRole()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TenantMemberUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMemberUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TenantMemberUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMemberUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMemberUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tenantmember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized tenantmember.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := tenantmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMemberUpdate) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantMemberUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantMemberUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantMemberUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmember.Table, tenantmember.Columns, sqlgraph.NewFieldSpec(tenantmember.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenantmember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenantmember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tenantmember.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tenantmember.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tenantmember.FieldDeletedBy, field.TypeInt)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.RoleTable,
			Columns: []string{tenantmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.RoleTable,
			Columns: []string{tenantmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TenantMemberUpdateOne is the builder for updating a single TenantMember entity.
type TenantMemberUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TenantMemberMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TenantMemberUpdateOne) SetUpdatedAt(v time.Time) *TenantMemberUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *TenantMemberUpdateOne) SetDeletedAt(v time.Time) *TenantMemberUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableDeletedAt(v *time.Time) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *TenantMemberUpdateOne) ClearDeletedAt() *TenantMemberUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *TenantMemberUpdateOne) SetDeletedBy(v int) *TenantMemberUpdateOne {
	_u.mutation.ResetDeletedBy()
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableDeletedBy(v *int) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// AddDeletedBy adds value to the "deleted_by" field.
func (_u *TenantMemberUpdateOne) AddDeletedBy(v int) *TenantMemberUpdateOne {
	_u.mutation.AddDeletedBy(v)
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *TenantMemberUpdateOne) ClearDeletedBy() *TenantMemberUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TenantMemberUpdateOne) SetTenantID(v int) *TenantMemberUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableTenantID(v *int) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TenantMemberUpdateOne) SetUserID(v int) *TenantMemberUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableUserID(v *int) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRoleID sets the "role_id" field.
func (_u *TenantMemberUpdateOne) SetRoleID(v int) *TenantMemberUpdateOne {
	_u.mutation.SetRoleID(v)
	return _u
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_u *TenantMemberUpdateOne) SetNillableRoleID(v *int) *TenantMemberUpdateOne {
	if v != nil {
		_u.SetRoleID(*v)
	}
	return _u
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdateOne) SetTenant(v *Tenant) *TenantMemberUpdateOne {
	return _u.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *TenantMemberUpdateOne) SetUser(v *User) *TenantMemberUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_u *TenantMemberUpdateOne) SetRole(v *Role) *TenantMemberUpdateOne {
	return _u.SetRoleID(v.ID)
}

// Mutation returns the TenantMemberMutation object of the builder.
func (_u *TenantMemberUpdateOne) Mutation() *TenantMemberMutation {
	return _u.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (_u *TenantMemberUpdateOne) ClearTenant() *TenantMemberUpdateOne {
	_u.mutation.ClearTenant()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TenantMemberUpdateOne) ClearUser() *TenantMemberUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearRole clears the "role" edge to the Role entity.
func (_u *TenantMemberUpdateOne) ClearRole() *TenantMemberUpdateOne {
	_u.mutation.ClearRole()
	return _u
}

// Where appends a list predicates to the TenantMemberUpdate builder.
func (_u *TenantMemberUpdateOne) Where(ps ...predicate.TenantMember) *TenantMemberUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TenantMemberUpdateOne) Select(field string, fields ...string) *TenantMemberUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TenantMember entity.
func (_u *TenantMemberUpdateOne) Save(ctx context.Context) (*TenantMember, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TenantMemberUpdateOne) SaveX(ctx context.Context) *TenantMember {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TenantMemberUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TenantMemberUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TenantMemberUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if tenantmember.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized tenantmember.UpdateDefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := tenantmember.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *TenantMemberUpdateOne) check() error {
	if _u.mutation.TenantCleared() && len(_u.mutation.TenantIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.tenant"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.user"`)
	}
	if _u.mutation.RoleCleared() && len(_u.mutation.RoleIDs()) > 0 {
		return errors.New(`generate: clearing a required unique edge "TenantMember.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TenantMemberUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TenantMemberUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TenantMemberUpdateOne) sqlSave(ctx context.Context) (_node *TenantMember, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantmember.Table, tenantmember.Columns, sqlgraph.NewFieldSpec(tenantmember.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`generate: missing "TenantMember.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantmember.FieldID)
		for _, f := range fields {
			if !tenantmember.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("generate: invalid field %q for query", f)}
			}
			if f != tenantmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmember.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(tenantmember.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(tenantmember.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(tenantmember.FieldDeletedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDeletedBy(); ok {
		_spec.AddField(tenantmember.FieldDeletedBy, field.TypeInt, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(tenantmember.FieldDeletedBy, field.TypeInt)
	}
	if _u.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.RoleTable,
			Columns: []string{tenantmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.RoleTable,
			Columns: []string{tenantmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TenantMember{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantmember.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
