// Code generated by ent, DO NOT EDIT.

package generate

import (
	"context"
	"errors"
	"fmt"
	"go-link/identity/internal/adapters/driven/db/ent/generate/role"
	"go-link/identity/internal/adapters/driven/db/ent/generate/tenant"
	"go-link/identity/internal/adapters/driven/db/ent/generate/tenantmember"
	"go-link/identity/internal/adapters/driven/db/ent/generate/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TenantMemberCreate is the builder for creating a TenantMember entity.
type TenantMemberCreate struct {
	config
	mutation *TenantMemberMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TenantMemberCreate) SetCreatedAt(v time.Time) *TenantMemberCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TenantMemberCreate) SetNillableCreatedAt(v *time.Time) *TenantMemberCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TenantMemberCreate) SetUpdatedAt(v time.Time) *TenantMemberCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TenantMemberCreate) SetNillableUpdatedAt(v *time.Time) *TenantMemberCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *TenantMemberCreate) SetDeletedAt(v time.Time) *TenantMemberCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *TenantMemberCreate) SetNillableDeletedAt(v *time.Time) *TenantMemberCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *TenantMemberCreate) SetDeletedBy(v int) *TenantMemberCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *TenantMemberCreate) SetNillableDeletedBy(v *int) *TenantMemberCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TenantMemberCreate) SetTenantID(v int) *TenantMemberCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *TenantMemberCreate) SetUserID(v int) *TenantMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *TenantMemberCreate) SetRoleID(v int) *TenantMemberCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (_c *TenantMemberCreate) SetTenant(v *Tenant) *TenantMemberCreate {
	return _c.SetTenantID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *TenantMemberCreate) SetUser(v *User) *TenantMemberCreate {
	return _c.SetUserID(v.ID)
}

// SetRole sets the "role" edge to the Role entity.
func (_c *TenantMemberCreate) SetRole(v *Role) *TenantMemberCreate {
	return _c.SetRoleID(v.ID)
}

// Mutation returns the TenantMemberMutation object of the builder.
func (_c *TenantMemberCreate) Mutation() *TenantMemberMutation {
	return _c.mutation
}

// Save creates the TenantMember in the database.
func (_c *TenantMemberCreate) Save(ctx context.Context) (*TenantMember, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TenantMemberCreate) SaveX(ctx context.Context) *TenantMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TenantMemberCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if tenantmember.DefaultCreatedAt == nil {
			return fmt.Errorf("generate: uninitialized tenantmember.DefaultCreatedAt (forgotten import generate/runtime?)")
		}
		v := tenantmember.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if tenantmember.DefaultUpdatedAt == nil {
			return fmt.Errorf("generate: uninitialized tenantmember.DefaultUpdatedAt (forgotten import generate/runtime?)")
		}
		v := tenantmember.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *TenantMemberCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`generate: missing required field "TenantMember.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`generate: missing required field "TenantMember.updated_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`generate: missing required field "TenantMember.tenant_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`generate: missing required field "TenantMember.user_id"`)}
	}
	if _, ok := _c.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`generate: missing required field "TenantMember.role_id"`)}
	}
	if len(_c.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`generate: missing required edge "TenantMember.tenant"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`generate: missing required edge "TenantMember.user"`)}
	}
	if len(_c.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`generate: missing required edge "TenantMember.role"`)}
	}
	return nil
}

func (_c *TenantMemberCreate) sqlSave(ctx context.Context) (*TenantMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TenantMemberCreate) createSpec() (*TenantMember, *sqlgraph.CreateSpec) {
	var (
		_node = &TenantMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tenantmember.Table, sqlgraph.NewFieldSpec(tenantmember.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(tenantmember.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantmember.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(tenantmember.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(tenantmember.FieldDeletedBy, field.TypeInt, value)
		_node.DeletedBy = &value
	}
	if nodes := _c.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.TenantTable,
			Columns: []string{tenantmember.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.UserTable,
			Columns: []string{tenantmember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tenantmember.RoleTable,
			Columns: []string{tenantmember.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantMember.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantMemberCreate) OnConflict(opts ...sql.ConflictOption) *TenantMemberUpsertOne {
	_c.conflict = opts
	return &TenantMemberUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantMemberCreate) OnConflictColumns(columns ...string) *TenantMemberUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantMemberUpsertOne{
		create: _c,
	}
}

type (
	// TenantMemberUpsertOne is the builder for "upsert"-ing
	//  one TenantMember node.
	TenantMemberUpsertOne struct {
		create *TenantMemberCreate
	}

	// TenantMemberUpsert is the "OnConflict" setter.
	TenantMemberUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantMemberUpsert) SetUpdatedAt(v time.Time) *TenantMemberUpsert {
	u.Set(tenantmember.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateUpdatedAt() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TenantMemberUpsert) SetDeletedAt(v time.Time) *TenantMemberUpsert {
	u.Set(tenantmember.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateDeletedAt() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TenantMemberUpsert) ClearDeletedAt() *TenantMemberUpsert {
	u.SetNull(tenantmember.FieldDeletedAt)
	return u
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TenantMemberUpsert) SetDeletedBy(v int) *TenantMemberUpsert {
	u.Set(tenantmember.FieldDeletedBy, v)
	return u
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateDeletedBy() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldDeletedBy)
	return u
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TenantMemberUpsert) AddDeletedBy(v int) *TenantMemberUpsert {
	u.Add(tenantmember.FieldDeletedBy, v)
	return u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TenantMemberUpsert) ClearDeletedBy() *TenantMemberUpsert {
	u.SetNull(tenantmember.FieldDeletedBy)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantMemberUpsert) SetTenantID(v int) *TenantMemberUpsert {
	u.Set(tenantmember.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateTenantID() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldTenantID)
	return u
}

// SetUserID sets the "user_id" field.
func (u *TenantMemberUpsert) SetUserID(v int) *TenantMemberUpsert {
	u.Set(tenantmember.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateUserID() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldUserID)
	return u
}

// SetRoleID sets the "role_id" field.
func (u *TenantMemberUpsert) SetRoleID(v int) *TenantMemberUpsert {
	u.Set(tenantmember.FieldRoleID, v)
	return u
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *TenantMemberUpsert) UpdateRoleID() *TenantMemberUpsert {
	u.SetExcluded(tenantmember.FieldRoleID)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TenantMemberUpsertOne) UpdateNewValues() *TenantMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(tenantmember.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TenantMemberUpsertOne) Ignore() *TenantMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantMemberUpsertOne) DoNothing() *TenantMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantMemberCreate.OnConflict
// documentation for more info.
func (u *TenantMemberUpsertOne) Update(set func(*TenantMemberUpsert)) *TenantMemberUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantMemberUpsertOne) SetUpdatedAt(v time.Time) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateUpdatedAt() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TenantMemberUpsertOne) SetDeletedAt(v time.Time) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateDeletedAt() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TenantMemberUpsertOne) ClearDeletedAt() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TenantMemberUpsertOne) SetDeletedBy(v int) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TenantMemberUpsertOne) AddDeletedBy(v int) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateDeletedBy() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TenantMemberUpsertOne) ClearDeletedBy() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantMemberUpsertOne) SetTenantID(v int) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateTenantID() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TenantMemberUpsertOne) SetUserID(v int) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateUserID() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *TenantMemberUpsertOne) SetRoleID(v int) *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *TenantMemberUpsertOne) UpdateRoleID() *TenantMemberUpsertOne {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *TenantMemberUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for TenantMemberCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantMemberUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TenantMemberUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TenantMemberUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (c *TenantMemberCreate) SetID(id int) *TenantMemberCreate {
	c.mutation.id = &id
	return c
}

// TenantMemberCreateBulk is the builder for creating many TenantMember entities in bulk.
type TenantMemberCreateBulk struct {
	config
	err      error
	builders []*TenantMemberCreate
	conflict []sql.ConflictOption
}

// Save creates the TenantMember entities in the database.
func (_c *TenantMemberCreateBulk) Save(ctx context.Context) ([]*TenantMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TenantMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TenantMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TenantMemberCreateBulk) SaveX(ctx context.Context) []*TenantMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TenantMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TenantMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TenantMember.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TenantMemberUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TenantMemberCreateBulk) OnConflict(opts ...sql.ConflictOption) *TenantMemberUpsertBulk {
	_c.conflict = opts
	return &TenantMemberUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TenantMemberCreateBulk) OnConflictColumns(columns ...string) *TenantMemberUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TenantMemberUpsertBulk{
		create: _c,
	}
}

// TenantMemberUpsertBulk is the builder for "upsert"-ing
// a bulk of TenantMember nodes.
type TenantMemberUpsertBulk struct {
	create *TenantMemberCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TenantMemberUpsertBulk) UpdateNewValues() *TenantMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(tenantmember.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TenantMember.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TenantMemberUpsertBulk) Ignore() *TenantMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TenantMemberUpsertBulk) DoNothing() *TenantMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TenantMemberCreateBulk.OnConflict
// documentation for more info.
func (u *TenantMemberUpsertBulk) Update(set func(*TenantMemberUpsert)) *TenantMemberUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TenantMemberUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TenantMemberUpsertBulk) SetUpdatedAt(v time.Time) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateUpdatedAt() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *TenantMemberUpsertBulk) SetDeletedAt(v time.Time) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateDeletedAt() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *TenantMemberUpsertBulk) ClearDeletedAt() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.ClearDeletedAt()
	})
}

// SetDeletedBy sets the "deleted_by" field.
func (u *TenantMemberUpsertBulk) SetDeletedBy(v int) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetDeletedBy(v)
	})
}

// AddDeletedBy adds v to the "deleted_by" field.
func (u *TenantMemberUpsertBulk) AddDeletedBy(v int) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.AddDeletedBy(v)
	})
}

// UpdateDeletedBy sets the "deleted_by" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateDeletedBy() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateDeletedBy()
	})
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (u *TenantMemberUpsertBulk) ClearDeletedBy() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.ClearDeletedBy()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *TenantMemberUpsertBulk) SetTenantID(v int) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateTenantID() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateTenantID()
	})
}

// SetUserID sets the "user_id" field.
func (u *TenantMemberUpsertBulk) SetUserID(v int) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateUserID() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateUserID()
	})
}

// SetRoleID sets the "role_id" field.
func (u *TenantMemberUpsertBulk) SetRoleID(v int) *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.SetRoleID(v)
	})
}

// UpdateRoleID sets the "role_id" field to the value that was provided on create.
func (u *TenantMemberUpsertBulk) UpdateRoleID() *TenantMemberUpsertBulk {
	return u.Update(func(s *TenantMemberUpsert) {
		s.UpdateRoleID()
	})
}

// Exec executes the query.
func (u *TenantMemberUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("generate: OnConflict was set for builder %d. Set it on the TenantMemberCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("generate: missing options for TenantMemberCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TenantMemberUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
