// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"go-link/billing/internal/adapters/driven/db/ent/generate"
	"go-link/billing/internal/adapters/driven/db/ent/generate/invoice"
	"go-link/billing/internal/adapters/driven/db/ent/generate/plan"
	"go-link/billing/internal/adapters/driven/db/ent/generate/predicate"
	"go-link/billing/internal/adapters/driven/db/ent/generate/subscription"

	"entgo.io/ent/dialect/sql"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next generate.Querier) generate.Querier {
	return generate.QuerierFunc(func(ctx context.Context, q generate.Query) (generate.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next generate.Querier) generate.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q generate.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The InvoiceFunc type is an adapter to allow the use of ordinary function as a Querier.
type InvoiceFunc func(context.Context, *generate.InvoiceQuery) (generate.Value, error)

// Query calls f(ctx, q).
func (f InvoiceFunc) Query(ctx context.Context, q generate.Query) (generate.Value, error) {
	if q, ok := q.(*generate.InvoiceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *generate.InvoiceQuery", q)
}

// The TraverseInvoice type is an adapter to allow the use of ordinary function as Traverser.
type TraverseInvoice func(context.Context, *generate.InvoiceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseInvoice) Intercept(next generate.Querier) generate.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseInvoice) Traverse(ctx context.Context, q generate.Query) error {
	if q, ok := q.(*generate.InvoiceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *generate.InvoiceQuery", q)
}

// The PlanFunc type is an adapter to allow the use of ordinary function as a Querier.
type PlanFunc func(context.Context, *generate.PlanQuery) (generate.Value, error)

// Query calls f(ctx, q).
func (f PlanFunc) Query(ctx context.Context, q generate.Query) (generate.Value, error) {
	if q, ok := q.(*generate.PlanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *generate.PlanQuery", q)
}

// The TraversePlan type is an adapter to allow the use of ordinary function as Traverser.
type TraversePlan func(context.Context, *generate.PlanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePlan) Intercept(next generate.Querier) generate.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePlan) Traverse(ctx context.Context, q generate.Query) error {
	if q, ok := q.(*generate.PlanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *generate.PlanQuery", q)
}

// The SubscriptionFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubscriptionFunc func(context.Context, *generate.SubscriptionQuery) (generate.Value, error)

// Query calls f(ctx, q).
func (f SubscriptionFunc) Query(ctx context.Context, q generate.Query) (generate.Value, error) {
	if q, ok := q.(*generate.SubscriptionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *generate.SubscriptionQuery", q)
}

// The TraverseSubscription type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubscription func(context.Context, *generate.SubscriptionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubscription) Intercept(next generate.Querier) generate.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubscription) Traverse(ctx context.Context, q generate.Query) error {
	if q, ok := q.(*generate.SubscriptionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *generate.SubscriptionQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q generate.Query) (Query, error) {
	switch q := q.(type) {
	case *generate.InvoiceQuery:
		return &query[*generate.InvoiceQuery, predicate.Invoice, invoice.OrderOption]{typ: generate.TypeInvoice, tq: q}, nil
	case *generate.PlanQuery:
		return &query[*generate.PlanQuery, predicate.Plan, plan.OrderOption]{typ: generate.TypePlan, tq: q}, nil
	case *generate.SubscriptionQuery:
		return &query[*generate.SubscriptionQuery, predicate.Subscription, subscription.OrderOption]{typ: generate.TypeSubscription, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
