// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"go-link/billing/internal/adapters/driven/db/ent/generate/invoice"
	"go-link/billing/internal/adapters/driven/db/ent/generate/plan"
	"go-link/billing/internal/adapters/driven/db/ent/generate/subscription"
	"go-link/billing/internal/adapters/driven/db/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	invoiceMixin := schema.Invoice{}.Mixin()
	invoiceMixinHooks1 := invoiceMixin[1].Hooks()
	invoice.Hooks[0] = invoiceMixinHooks1[0]
	invoiceMixinInters1 := invoiceMixin[1].Interceptors()
	invoice.Interceptors[0] = invoiceMixinInters1[0]
	invoiceMixinFields0 := invoiceMixin[0].Fields()
	_ = invoiceMixinFields0
	invoiceFields := schema.Invoice{}.Fields()
	_ = invoiceFields
	// invoiceDescCreatedAt is the schema descriptor for created_at field.
	invoiceDescCreatedAt := invoiceMixinFields0[0].Descriptor()
	// invoice.DefaultCreatedAt holds the default value on creation for the created_at field.
	invoice.DefaultCreatedAt = invoiceDescCreatedAt.Default.(func() time.Time)
	// invoiceDescUpdatedAt is the schema descriptor for updated_at field.
	invoiceDescUpdatedAt := invoiceMixinFields0[1].Descriptor()
	// invoice.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	invoice.DefaultUpdatedAt = invoiceDescUpdatedAt.Default.(func() time.Time)
	// invoice.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	invoice.UpdateDefaultUpdatedAt = invoiceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// invoiceDescTenantID is the schema descriptor for tenant_id field.
	invoiceDescTenantID := invoiceFields[1].Descriptor()
	// invoice.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	invoice.TenantIDValidator = invoiceDescTenantID.Validators[0].(func(int) error)
	// invoiceDescCurrency is the schema descriptor for currency field.
	invoiceDescCurrency := invoiceFields[3].Descriptor()
	// invoice.CurrencyValidator is a validator for the "currency" field. It is called by the builders before save.
	invoice.CurrencyValidator = func() func(string) error {
		validators := invoiceDescCurrency.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(currency string) error {
			for _, fn := range fns {
				if err := fn(currency); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	planMixin := schema.Plan{}.Mixin()
	planMixinHooks1 := planMixin[1].Hooks()
	plan.Hooks[0] = planMixinHooks1[0]
	planMixinInters1 := planMixin[1].Interceptors()
	plan.Interceptors[0] = planMixinInters1[0]
	planMixinFields0 := planMixin[0].Fields()
	_ = planMixinFields0
	planFields := schema.Plan{}.Fields()
	_ = planFields
	// planDescCreatedAt is the schema descriptor for created_at field.
	planDescCreatedAt := planMixinFields0[0].Descriptor()
	// plan.DefaultCreatedAt holds the default value on creation for the created_at field.
	plan.DefaultCreatedAt = planDescCreatedAt.Default.(func() time.Time)
	// planDescUpdatedAt is the schema descriptor for updated_at field.
	planDescUpdatedAt := planMixinFields0[1].Descriptor()
	// plan.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plan.DefaultUpdatedAt = planDescUpdatedAt.Default.(func() time.Time)
	// plan.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plan.UpdateDefaultUpdatedAt = planDescUpdatedAt.UpdateDefault.(func() time.Time)
	// planDescName is the schema descriptor for name field.
	planDescName := planFields[0].Descriptor()
	// plan.NameValidator is a validator for the "name" field. It is called by the builders before save.
	plan.NameValidator = func() func(string) error {
		validators := planDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// planDescBasePrice is the schema descriptor for base_price field.
	planDescBasePrice := planFields[1].Descriptor()
	// plan.BasePriceValidator is a validator for the "base_price" field. It is called by the builders before save.
	plan.BasePriceValidator = planDescBasePrice.Validators[0].(func(float64) error)
	// planDescPeriod is the schema descriptor for period field.
	planDescPeriod := planFields[2].Descriptor()
	// plan.PeriodValidator is a validator for the "period" field. It is called by the builders before save.
	plan.PeriodValidator = func() func(string) error {
		validators := planDescPeriod.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(period string) error {
			for _, fn := range fns {
				if err := fn(period); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// planDescIsActive is the schema descriptor for is_active field.
	planDescIsActive := planFields[4].Descriptor()
	// plan.DefaultIsActive holds the default value on creation for the is_active field.
	plan.DefaultIsActive = planDescIsActive.Default.(bool)
	subscriptionMixin := schema.Subscription{}.Mixin()
	subscriptionMixinHooks1 := subscriptionMixin[1].Hooks()
	subscription.Hooks[0] = subscriptionMixinHooks1[0]
	subscriptionMixinInters1 := subscriptionMixin[1].Interceptors()
	subscription.Interceptors[0] = subscriptionMixinInters1[0]
	subscriptionMixinFields0 := subscriptionMixin[0].Fields()
	_ = subscriptionMixinFields0
	subscriptionFields := schema.Subscription{}.Fields()
	_ = subscriptionFields
	// subscriptionDescCreatedAt is the schema descriptor for created_at field.
	subscriptionDescCreatedAt := subscriptionMixinFields0[0].Descriptor()
	// subscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	subscription.DefaultCreatedAt = subscriptionDescCreatedAt.Default.(func() time.Time)
	// subscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionDescUpdatedAt := subscriptionMixinFields0[1].Descriptor()
	// subscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscription.DefaultUpdatedAt = subscriptionDescUpdatedAt.Default.(func() time.Time)
	// subscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscription.UpdateDefaultUpdatedAt = subscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionDescTenantID is the schema descriptor for tenant_id field.
	subscriptionDescTenantID := subscriptionFields[0].Descriptor()
	// subscription.TenantIDValidator is a validator for the "tenant_id" field. It is called by the builders before save.
	subscription.TenantIDValidator = subscriptionDescTenantID.Validators[0].(func(int) error)
	// subscriptionDescCancelAtPeriodEnd is the schema descriptor for cancel_at_period_end field.
	subscriptionDescCancelAtPeriodEnd := subscriptionFields[5].Descriptor()
	// subscription.DefaultCancelAtPeriodEnd holds the default value on creation for the cancel_at_period_end field.
	subscription.DefaultCancelAtPeriodEnd = subscriptionDescCancelAtPeriodEnd.Default.(bool)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
