// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// InvoicesColumns holds the columns for the "invoices" table.
	InvoicesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeFloat64},
		{Name: "currency", Type: field.TypeString, Size: 3},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"PENDING", "PAID", "FAILED", "REFUNDED"}, Default: "PENDING"},
		{Name: "payment_id", Type: field.TypeString, Nullable: true},
		{Name: "subscription_id", Type: field.TypeInt},
	}
	// InvoicesTable holds the schema information for the "invoices" table.
	InvoicesTable = &schema.Table{
		Name:       "invoices",
		Columns:    InvoicesColumns,
		PrimaryKey: []*schema.Column{InvoicesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "invoices_subscriptions_invoices",
				Columns:    []*schema.Column{InvoicesColumns[10]},
				RefColumns: []*schema.Column{SubscriptionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "invoice_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[5]},
			},
			{
				Name:    "invoice_subscription_id",
				Unique:  false,
				Columns: []*schema.Column{InvoicesColumns[10]},
			},
		},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_by", Type: field.TypeInt, Nullable: true},
		{Name: "name", Type: field.TypeString, Size: 100},
		{Name: "description", Type: field.TypeString, Nullable: true, Size: 200},
		{Name: "base_price", Type: field.TypeFloat64},
		{Name: "period", Type: field.TypeString, Size: 20},
		{Name: "features", Type: field.TypeJSON, Nullable: true},
		{Name: "is_active", Type: field.TypeBool, Default: true},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "deleted_by", Type: field.TypeInt, Nullable: true},
		{Name: "tenant_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"ACTIVE", "PENDING", "PAID", "PAST_DUE", "CANCELED"}, Default: "PENDING"},
		{Name: "current_period_start", Type: field.TypeTime},
		{Name: "current_period_end", Type: field.TypeTime},
		{Name: "cancel_at_period_end", Type: field.TypeBool, Default: false},
		{Name: "plan_id", Type: field.TypeInt},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_plans_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[10]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "subscription_tenant_id",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[5]},
			},
			{
				Name:    "subscription_status",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionsColumns[6]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		InvoicesTable,
		PlansTable,
		SubscriptionsTable,
	}
)

func init() {
	InvoicesTable.ForeignKeys[0].RefTable = SubscriptionsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = PlansTable
}
